### ISSUE TITLE
Fields getting syntax-colored as keywords

### ISSUE THREAD

**Issue by cjprieb** [ing-bank/vscode-psl#19]
When referencing a property on a class that has the same name as a keyword (such as `type` or `write`), the grammar considers it a keyword, and it gets colored as a keyword instead of as a property.
![psl syntax coloring - keywords](https://user-images.githubusercontent.com/13191550/44421342-d7ffeb80-a545-11e8-864a-9e854d993286.png)

**Comment by atiplea** [comment]
The solution seems to be going from `\b` to `\b(?<!\.)` as the left word delimiter.

![image](https://user-images.githubusercontent.com/34708329/44488363-de32bc80-a658-11e8-95bc-c6654fb8056a.png)

I will make the assumption that this only needs to apply when a `.` is on the left.
