### ISSUE TITLE
Can not be installed on Community Edition

### ISSUE THREAD

**Issue by IgorTopalov** [ing-bank/vscode-psl#20]
Hello, 
I've tried to install this extension on MS VS community Edition 2017.
Complains:
--+
8/31/2018 1:59:54 AM - Microsoft VSIX Installer
8/31/2018 1:59:54 AM - -------------------------------------------
8/31/2018 1:59:54 AM - vsixinstaller.exe version:
8/31/2018 1:59:54 AM - 15.8.3237
8/31/2018 1:59:54 AM - -------------------------------------------
8/31/2018 1:59:54 AM - Command line parameters:
8/31/2018 1:59:54 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\NC\Downloads\ing-bank.vscode-psl-1.4.1.vsix
8/31/2018 1:59:54 AM - -------------------------------------------
8/31/2018 1:59:54 AM - Microsoft VSIX Installer
8/31/2018 1:59:54 AM - -------------------------------------------
8/31/2018 1:59:54 AM - Initializing Install...
8/31/2018 1:59:55 AM - Extension Details...
8/31/2018 1:59:55 AM - 	Identifier         : vscode-psl
8/31/2018 1:59:55 AM - 	Name               : vscode-psl
8/31/2018 1:59:55 AM - 	Author             : ing-bank
8/31/2018 1:59:55 AM - 	Version            : 1.4.1
8/31/2018 1:59:55 AM - 	Description        : Profile Scripting Language support
8/31/2018 1:59:55 AM - 	Locale             : en-US
8/31/2018 1:59:55 AM - 	MoreInfoURL        : 
8/31/2018 1:59:55 AM - 	InstalledByMSI     : False
8/31/2018 1:59:55 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
8/31/2018 1:59:55 AM - 
8/31/2018 1:59:55 AM - 	SignatureState     : Unsigned
8/31/2018 1:59:55 AM - 	Supported Products : 
8/31/2018 1:59:55 AM - 		Microsoft.VisualStudio.Code
8/31/2018 1:59:55 AM - 			Version : 
8/31/2018 1:59:55 AM - 
8/31/2018 1:59:55 AM - 	References         : 
8/31/2018 1:59:55 AM - Signature Details...
8/31/2018 1:59:55 AM - 	Extension is not signed.
8/31/2018 1:59:55 AM - 
8/31/2018 1:59:55 AM - Searching for applicable products...
8/31/2018 1:59:55 AM - Found installed product - Global Location
8/31/2018 1:59:55 AM - Found installed product - Visual Studio Community 2017
8/31/2018 1:59:55 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by atiplea** [comment]
Hi Igor,

This plugin is for Visual Studio **Code**, not Visual Studio. The two are based on different platforms and their plugins (despite having the same file extension) are not cross-compatible.
