### ISSUE TITLE
Static variables are above local variables

### ISSUE THREAD

**Issue by kewtree1408** [ing-bank/vscode-psl#36]
Check that static variables are above local variables.
Show the diagnosis info in this case:
```
type String test = ""
type ByteString errorMsg = ""
type static ZUtxTesttest
```

and fix it:
```
type static ZUtxTesttest
type ByteString errorMsg = ""
type String test = ""
```
PS: also, maybe, we can sort the variable names.

**Comment by SOliveiraING** [comment]
Rule no longer relevant below guideline applies for static classes:

Declare together, separated from other declarations, generally either first or last; or may be declared right before their first use.
