### ISSUE TITLE
[Feature] Create profile project with default folders

### ISSUE THREAD

**Issue by joelgomes85** [ing-bank/vscode-psl#60]
It would be nice to have the option to create a new project with profile default folders.

![image](https://user-images.githubusercontent.com/22542639/50002008-9da7d780-ff96-11e8-8f8e-1531c77682a7.png)

**Comment by kdrozd** [comment]
Against many wishes, VSCode is still a fancy code **editor**, not an IDE. Maybe you need an upgrade of your Eclipse plugins?

**Comment by joelgomes85** [comment]
My eclipse works just fine.
I'm enjoying vscode with psl plugin and this was just a suggestion, can be closed ;)
