### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sisamala** [ing-bank/vscode-psl#97]
- Issue Type: `Performance`
- Extension Name: `vscode-psl`
- Extension Version: `1.10.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.37.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\adnan\ing-bank.vscode-psl-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by atiplea** [comment]
Hi @sisamala, thanks for opening this issue. Can you please include more information? It seems as though there was a cpuprofile that was wasn't attached here.

**Comment by SOliveiraING** [comment]
Requested details not provided closing the issue assuming that is no longer occurring.
If still occurring please reopen and provide details.
